import * as themeColors from './themeColors'

const darkTheme = {
  colors: {
    accordion: themeColors.primary,
    active: themeColors.lightAccent,
    background: themeColors.darkestShade,
    banner: themeColors.lightShade,
    border: themeColors.darkestShade,
    button: themeColors.darkAccent,
    buttonLight: themeColors.light,
    buttonText: themeColors.light,
    buttonDarkText: themeColors.darkShade,
    cardBackground: themeColors.darkShade,
    cardText: themeColors.light,
    chatBotHeaderText: themeColors.primary,
    checkmark: themeColors.lightAccent,
    ctaButton: themeColors.primary,
    ctaButtonDark: themeColors.light,
    dividerLine: themeColors.light,
    dividerText: themeColors.light,
    drawer: themeColors.darkShade,
    drawerText: themeColors.light,
    drawerHover: themeColors.primary,
    drawerHoverText: themeColors.light,
    dropdownHover: themeColors.primary,
    dropdownHoverText: themeColors.light,
    footer: themeColors.darkShade,
    footerText: themeColors.light,
    formBackground: themeColors.light,
    formText: themeColors.darkShade,
    grid: themeColors.primary,
    header: themeColors.darkAccent,
    headerText: themeColors.light,
    helpIcon: themeColors.primary,
    hero: themeColors.primary,
    heroText: themeColors.light,
    inputNoFocus: themeColors.lightShade,
    inputFocus: themeColors.light,
    logoBackground: themeColors.light,
    logoText: themeColors.primary,
    message: themeColors.darkAccent,
    modal: themeColors.darkAccent,
    modalText: themeColors.light,
    navBar: themeColors.darkShade,
    navBarText: themeColors.light,
    navBarHover: themeColors.lightAccent,
    navBarHoverText: themeColors.primary,
    text: themeColors.light,
    textOnDark: themeColors.light,
    select: themeColors.lightAccent,
  },
  layout: {
    navBarHeight: '50px',
    drawerWidth: '220px',
  },
  breakpoints: [500, 700],
  toggleBorder: '#FFF',
  gradient: 'linear-gradient(#0B0B19, #0A1432)',
  //gradient: themeColors.darkShade,
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  fontHeader: '\'Playfair Display\', serif;',
  fontBody: '\'STIX Two Text\', serif'
}

export default darkTheme